# eslint configuration
root: true
extends: ['next', 'turbo', 'prettier']
rules:
  '@next/next/no-html-link-for-pages': error
  '@next/next/no-img-element': error
  'import/no-anonymous-default-export': error
  'jsx-a11y/alt-text': error
  'react-hooks/exhaustive-deps': error

# Overrides for specific file patterns
overrides:
  - files: ['packages/**']
    extends: ['turbo', 'prettier']
    rules:
      '@next/next/no-html-link-for-pages': off
