# eslint configuration
root: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'next'
  - 'turbo'
  - 'prettier'
rules:
  '@next/next/no-html-link-for-pages': 'error'
  '@next/next/no-img-element': 'error'
  'import/no-anonymous-default-export': 'error'
  'jsx-a11y/alt-text': 'error'
  'react-hooks/exhaustive-deps': 'error'
  '@typescript-eslint/consistent-type-imports': 'error'

ignorePatterns:
  - '**/dist'
  - '**/out'

# Overrides for specific file patterns
overrides:
  - files: ['examples/**']
    extends: ['turbo', 'prettier']
    rules:
      '@typescript-eslint/no-unused-vars': off

  - files: ['packages/**']
    extends: ['turbo', 'prettier']
    rules:
      '@next/next/no-html-link-for-pages': off
