name: Validate PR

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - README.md
    - CHANGELOG.md

jobs:
  build:
    runs-on: ubuntu-latest
    name: 🛠️ Build

    steps:
    - name: ⬇️ Checkout repo
      uses: actions/checkout@v4

    - name: ⎔ Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: ⎔ Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: "pnpm"

    - name: 📥 Download deps
      run: pnpm install

    - name: 🛠️ Build
      run: pnpm build

    - name: 🧪 Test
      run: pnpm test
